# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{ pkgs, lib }:

let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
merge
  (merge
    (merge
      (merge
      {
        "be5invis"."vscode-custom-css" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-custom-css";
          publisher = "be5invis";
          version = "7.4.2";
          sha256 = "1k10k03al0lvj9zf5g9s8bgikq2l47ispgk5d7jnsj53dc2mkwdr";

        };
        "brandonkirbyson"."vscode-animations" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-animations";
          publisher = "brandonkirbyson";
          version = "2.0.7";
          sha256 = "13whqqlv46mngg94pyy87s11im3ixb1rf4ngdd8jhk4znvbqph2d";

        };
        "robbowen"."synthwave-vscode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "synthwave-vscode";
          publisher = "robbowen";
          version = "0.1.18";
          sha256 = "0f52fbk3c8r0y2j9kcg5a95rz40650lh1dccz17hhf1ja0ymmvlr";

        };
        "eliverlara"."andromeda" = vscode-utils.extensionFromVscodeMarketplace {
          name = "andromeda";
          publisher = "eliverlara";
          version = "1.8.2";
          sha256 = "05rrgvpqngfrwa289jw5kff9ns52ba24nzrfcl1rvf55w9gb7gxs";

        };
        "wicked-labs"."wvsc-serendipity" = vscode-utils.extensionFromVscodeMarketplace {
          name = "wvsc-serendipity";
          publisher = "wicked-labs";
          version = "1.66.0";
          sha256 = "1l484q90kq5yzfxbaz7bfdiqbick92g70gakxbmcxq48ign85wlg";

        };
      }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) { }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) { }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) { }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) { })